src/main/java/ch/ultrasoft/guieditorjsf/bean/UserBean.java
package ch.ultrasoft.guieditorjsf.bean;

import java.io.IOException;
import java.io.Serializable;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import ch.ultrasoft.guieditorjsf.model.User;
import ch.ultrasoft.guieditorjsf.model.UserRole;
import ch.ultrasoft.guieditorjsf.persistence.DataRepository;

/**
 *
 * @author r0y
 *
 */
@SuppressWarnings("serial")
@SessionScoped
@Named("userBean")
public class UserBean implements Serializable {

	@Inject
	@DataRepository
	private EntityManager em;

	private String user;
	private String password;

	private FacesContext context;
	private ExternalContext externalContext;
	private HttpServletRequest request;
	private HttpSession session;

	public UserBean() {
		super();
	}

	@PostConstruct
	public void init() {
		context = FacesContext.getCurrentInstance();
		externalContext = context.getExternalContext();
		request = (HttpServletRequest) externalContext.getRequest();
		session = request.getSession(false);

	}

	public void login() {
		context = FacesContext.getCurrentInstance();
		externalContext = context.getExternalContext();
		request = (HttpServletRequest) externalContext.getRequest();
		System.out.println("sdfsa");
		try {
			int idUser = (int) em
					.createQuery(
							"SELECT u.id FROM User u WHERE username = :username")
					.setParameter("username", user).getSingleResult();
			request.login("" + idUser, password);
			user = find(user, password, idUser);
			externalContext.getSessionMap().put("user", user);
			externalContext.redirect("index.html");
			System.out.println("Fertig");
		} catch (Exception e) {
			e.printStackTrace();
			context = FacesContext.getCurrentInstance();
			context.addMessage(null, new FacesMessage(
					FacesMessage.SEVERITY_ERROR, "Access denied", null));
		}

	}

	public String find(String user, String pass, int id) {

		User u = em.find(User.class, id);

		if (user.equals(u.getUsername()) && pass.equals(u.getPassword())) {
			return user;
		}
		return "not authorized";
	}

	public void logout() {

		// Destroys the session for this user.
		if (session != null)
			session.invalidate();

		// Redirects back to the initial page.
		try {
			externalContext.redirect("./");
		} catch (IOException e) {
			e.printStackTrace();
		}

	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getUser() {
		return user;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = getHashMd5(password);
	}

	public String getHashMd5(String clearPass) {
		MessageDigest m;
		try {
			m = MessageDigest.getInstance("MD5");
			m.update(clearPass.getBytes(), 0, clearPass.length());
			return new BigInteger(1, m.digest()).toString(16);
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		return "";
	}

	public boolean isAdmin() {
		List<UserRole> listUserRole = em
				.createQuery(
						"FROM UserRole ur WHERE ur.user.username = :userName AND ur.role.id = 1")
				.setParameter("userName", user).getResultList();
		if (listUserRole.isEmpty()) {
			return false;
		}
		return true;
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/model/Role.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.model;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author manigley
 */
@Entity
@Table(name = "roles")
public class Role implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "id_role")
	private Integer id;
	@Column(name = "role")
	private String role;

	public Role() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public String toString() {
		return "Role [id=" + id + "]";
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/model/User.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.model;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author kenny
 */
@Entity
@Table(name = "jusers")
public class User implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "id_juser")
	private int id;
	@Column(name = "username")
	private String username;
	@Column(name = "password")
	private String password;

	public User() {
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getId() {
		return id;
	}

	public void setId(int id_user) {
		this.id = id_user;
	}

}

src/main/java/ch/ultrasoft/guieditorjsf/controller/AbstractController.java
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.el.ELContext;
import javax.enterprise.context.SessionScoped;
import javax.faces.FacesException;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.servlet.http.HttpServletRequest;

import ch.ultrasoft.guieditorjsf.persistence.DataRepository;

@SessionScoped
public abstract class AbstractController<T> implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private T selectedRecord;
	private List<T> recordList;
	private Class<T> clazz;
	private List<T> filteredRecordList = new ArrayList<>();

	@Inject
	@DataRepository
	private EntityManager em;

	public AbstractController() {
	}

	public AbstractController(Class<T> clazz) {
		this.clazz = clazz;
		try {
			selectedRecord = clazz.newInstance();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
	}

	public void save() {
		EntityTransaction tx = em.getTransaction();
		try {
			tx.begin();
			em.persist(selectedRecord);
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
		}
		clear();
		doHardReload();
		printFacesMessage("Saved", "");
	}

	public void delete(Object o) {
		EntityTransaction tx = em.getTransaction();
		try {
			tx.begin();
			em.remove(o);
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
		}
		clear();
		doHardReload();
		printFacesMessage("DELETED", "");
	}

	protected void printFacesMessage(String summary, String detail) {
		FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage(summary, detail));
	}

	public void clear() {
		try {
			em.clear();
			selectedRecord = clazz.newInstance();
			loadRecordList();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
	}

	public void doHardReload() {
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		try {
			ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void loadRecordList() {
		recordList = em.createQuery("FROM " + clazz.getSimpleName()).getResultList();
		filteredRecordList = recordList;
	}

	public List<T> getRecordList() {
		loadRecordList();
		return recordList;
	}

	public void setRecordList(List<T> recordList) {
		this.recordList = recordList;
	}

	public List<T> getFilteredRecordList() {
		if (filteredRecordList == null) {
			loadRecordList();
		}
		return filteredRecordList;
	}

	public void setFilteredRecordList(List<T> filteredRecordList) {
		this.filteredRecordList = filteredRecordList;
	}

	public T getSelectedRecord() {
		return selectedRecord;
	}

	public void setSelectedRecord(T selectedRecord) {
		this.selectedRecord = selectedRecord;
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/RoleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import ch.ultrasoft.guieditorjsf.model.Role;

/**
 *
 * @author kenny
 */
@Named("roleController")
@SessionScoped
public class RoleController extends AbstractController<Role> implements Serializable {
	
	private static final long serialVersionUID = 1L;

	public RoleController(){
		super(Role.class);
	}
	
	//@TestAnnotation
	public void test() {
		printFacesMessage("Hello", "this is a test");
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/ScheduleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import ch.ultrasoft.guieditorjsf.model.Schedule;

/**
 *
 * @author kenny
 */
@Named("scheduleController")
@SessionScoped
public class ScheduleController extends AbstractController<Schedule> implements Serializable {

	private static final long serialVersionUID = 1L;

	public ScheduleController() {
		super(Schedule.class);
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

import ch.ultrasoft.guieditorjsf.bean.UserBean;
import ch.ultrasoft.guieditorjsf.model.Role;
import ch.ultrasoft.guieditorjsf.model.User;
import ch.ultrasoft.guieditorjsf.model.UserRole;
import ch.ultrasoft.guieditorjsf.persistence.DataRepository;

/**
 *
 * @author kenny
 */
@SuppressWarnings("serial")
@Named("userController")
@SessionScoped
public class UserController implements Serializable {

	@Inject
	@DataRepository
	private EntityManager em;

	private String controlPassword;
	private String password;

	@Inject
	UserBean userbean;

	private User selectedUser;
	private boolean isAdmin = false;

	@PostConstruct
	void init() {

		System.out.println("init User");
		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	@SuppressWarnings("unchecked")
	public void updateUser() {
		
		if (password.equals(controlPassword)) {
			selectedUser.setPassword(password);
			selectedUser.setPassword(userbean.getHashMd5(selectedUser
					.getPassword()));
		} 
		EntityTransaction tx = em.getTransaction();
		tx.begin();
		em.merge(selectedUser);
		tx.commit();

		if (isAdmin) {
			UserRole userrole = new UserRole();
			userrole.setUser(selectedUser);
			userrole.setRole(em.find(Role.class, 1));
			tx.begin();
			em.merge(userrole);
			tx.commit();
		} else if (selectedUser.getId() != 0) {
			List<UserRole> listUserRole = em
					.createQuery(
							"FROM UserRole ur WHERE ur.user.id = :idUser AND ur.role.id = 1")
					.setParameter("idUser", selectedUser.getId())
					.getResultList();
			for (UserRole ur : listUserRole) {
				tx.begin();
				em.remove(ur);
				tx.commit();
			}
		}
		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	public void deleteUser() {
		EntityTransaction tx = em.getTransaction();
		@SuppressWarnings("unchecked")
		List<UserRole> lustUserRole = em
				.createQuery("FROM UserRole ur WHERE ur.user.id =:idUser")
				.setParameter("idUser", selectedUser.getId()).getResultList();
		for (UserRole ur : lustUserRole) {
			tx.begin();
			em.remove(ur);
			tx.commit();
		}
		tx.begin();
		em.remove(selectedUser);
		tx.commit();

		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	public void addUser() {
		password = "";
		controlPassword = "";
		isAdmin = false;
		selectedUser = new User();
	}

	public void cancel() {
		selectedUser = new User();
		controlPassword = "";
		password = "1";
	}

	public void updatePassword() {
		if (password == controlPassword) {
			selectedUser.setPassword(password);
		}
	}

	// GETTER & SETTER

	public List<User> getUserlist() {
		return em.createQuery("FROM User u").getResultList();
	}

	public User getSelectedUser() {
		return selectedUser;
	}

	public void setSelectedUser(User selectedUser) {
		this.selectedUser = selectedUser;
	}

	public boolean getAdmin() {
		if (selectedUser != null) {
			List<UserRole> listUserRole = em
					.createQuery(
							"FROM UserRole ur WHERE ur.user.id = :idUser AND ur.role.id = 1")
					.setParameter("idUser", selectedUser.getId())
					.getResultList();

			if (!listUserRole.isEmpty()) {
				return true;
			}
		}
		return false;
	}

	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getControlPassword() {
		return controlPassword;
	}

	public void setControlPassword(String controlPassword) {
		this.controlPassword = controlPassword;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

src/main/java/ch/ultrasoft/guieditorjsf/controller/ValidationController.java
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.apache.log4j.Logger;

@Named("validationController2")
@SessionScoped
public class ValidationController implements Serializable {

	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger.getLogger(ValidationController.class);

	public void save() {
		LOGGER.debug("save() is called");
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Hello from bean");
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void delete() {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Hello from bean");
		FacesContext.getCurrentInstance().addMessage(null, msg);
		LOGGER.debug("doIt() is called");
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/viewcontroller/RoleViewController.java
package ch.ultrasoft.guieditorjsf.viewcontroller;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;

import ch.ultrasoft.guieditorjsf.viewmodel.UltraDialogModel;
import ch.ultrasoft.guieditorjsf.viewmodel.UltraTableModel;

@SessionScoped
@Named("roleViewController")
public class RoleViewController extends AbstractViewController {

	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger.getLogger(RoleViewController.class);

	public RoleViewController() {

	}

	public UltraTableModel getTableModel() {
		return (UltraTableModel) getService().findViewElement(new Long(7));
	}

	public UltraDialogModel getDialogModel() {
		return (UltraDialogModel) getService().findViewElement(new Long(10));
	}
}

src/main/webapp/pages/views/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="../templates/template.xhtml">

	<ui:define name="template">


		
	</ui:define>
</ui:composition>

src/main/webapp/pages/views/role.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="../templates/template.xhtml"
	xmlns:us="http://java.sun.com/jsf/composite/us">

	<ui:define name="template">

		<us:updateDialog id="ultraDialog"
			dialog="#{roleViewController.dialogModel}"
			enityController="#{roleController}" viewController="#{roleViewController}" />

		<us:dataTable id="ultraTable"
			dataTable="#{roleViewController.tableModel}" />

	</ui:define>
</ui:composition>

src/main/webapp/pages/views/schedule.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="../templates/template.xhtml">

	<ui:define name="template">

		<p:dialog id="updateDialog" widgetVar="updateDialog" resizable="false"
			header="Edit">
			<h:form id="updateForm">
				<h:panelGrid columns="2">
					<h:outputText value="Name" />
					<p:inputText value="#{scheduleController.selectedRecord.name}" />
				</h:panelGrid>

				<p:commandButton value="update"
					actionListener="#{scheduleController.save()}"
					oncomplete="PF('updateDialog').hide();" update=":tableForm" />
				<p:commandButton value="close"
					oncomplete="PF('updateDialog').hide();" />

			</h:form>
		</p:dialog>

		<h:form id="tableForm">
			<p:dataTable value="#{scheduleController.recordList}" var="r">
				<p:column headerText="Name">
					<h:outputText value="#{r.name}" title="#{r}" />
				</p:column>
				<p:column headerText="start">
					<h:outputText value="#{r.start}">
						<f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
					</h:outputText>
				</p:column>
				<p:column headerText="end">
					<h:outputText value="#{r.end}">
						<f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
					</h:outputText>
				</p:column>
				<p:column>
					<p:commandButton icon="fa fa-edit"
						actionListener="#{scheduleController.setSelectedRecord(r)}"
						oncomplete="PF('updateDialog').show();" update=":updateDialog" />
					<p:commandButton icon="fa fa-trash"
						actionListener="#{scheduleController.delete(r)}"
						update=":tableForm" />
				</p:column>
			</p:dataTable>

			<p:commandButton icon="fa fa-plus-circle"
				actionListener="#{scheduleController.clear()}"
				oncomplete="PF('updateDialog').show();" update=":updateDialog" />
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/views/user.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="../templates/template.xhtml">

	<ui:define name="template">


		<p:dialog id="delDialog" widgetVar="delDialog" header="Löschen"
			closable="false" resizable="false">
			<h:form id="delForm">
				<h:panelGrid columns="1" style="margin: auto;">
					<h:outputText value="Soll der User gelöscht werden?" />
				</h:panelGrid>
				<h:panelGrid columns="2" style="margin: 0 auto;">
					<p:commandButton actionListener="#{userController.deleteUser()}"
						update=":tableForm" icon="ui-icon-check"
						oncomplete="PF('delDialog').hide();" />
					<p:commandButton update=":tableForm" icon="ui-icon-cancel"
						oncomplete="PF('delDialog').hide();"
						actionListener="#{userController.cancel()}" />
				</h:panelGrid>
			</h:form>
		</p:dialog>

		<p:dialog id="addDialog" widgetVar="addDialog" resizable="false"
			closable="false"
			header="Add user: #{userController.selectedUser.username}">
			<h:form id="addForm">

				<h:panelGrid columns="2">
					<h:outputText value="Username" />
					<p:inputText value="#{userController.selectedUser.username}" />
					<h:outputText value="Password" />
					<p:password value="#{userController.password}">
						<p:ajax event="keyup" update="add" />
					</p:password>
					<h:outputText value="Password repeat" />
					<p:password value="#{userController.controlPassword}">
						<p:ajax event="keyup" update="add" />
						</p:password>
				</h:panelGrid>

				<p:commandButton value="add" id="add"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('addDialog').hide();"
					disabled="#{userController.password ne userController.controlPassword}"
					update=":tableForm" />
				<p:commandButton value="close"
					oncomplete="PF('addDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>

		<p:dialog id="updateDialog" widgetVar="updateDialog" resizable="false"
			closable="false"
			header="Update user: #{userController.selectedUser.username}">
			<h:form id="updateForm">

				<h:panelGrid columns="2">
					<h:outputText value="Username" />
					<p:inputText value="#{userController.selectedUser.username}" />
					<h:outputText value="Admin" />
					<p:selectBooleanCheckbox value="#{userController.admin}"
						disabled="#{userController.selectedUser.id eq 0}" />
				</h:panelGrid>

				<p:commandButton value="update" id="update"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('updateDialog').hide();"
					update=":tableForm" />
				<p:commandButton value="close"
					oncomplete="PF('updateDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>

		<p:dialog id="passDialog" widgetVar="passDialog" resizable="false"
			closable="false"
			header="Update password: #{userController.selectedUser.username}">
			<h:form id="passForm">

				<h:panelGrid columns="2">
					<h:outputText value="Password" />
					<p:password value="#{userController.password}">
						<p:ajax event="keyup" update="updatePass" />
					</p:password>
					<h:outputText value="Password repeat" />
					<p:password value="#{userController.controlPassword}">
						<p:ajax event="keyup" update="updatePass" />
					</p:password>
				</h:panelGrid>

				<p:commandButton value="update" id="updatePass"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('passDialog').hide();"
					disabled="#{userController.password ne userController.controlPassword}"
					update=":tableForm:userTable" />
				<p:commandButton value="close" oncomplete="PF('passDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>


		<h:form id="tableForm">
			<p:dataTable id="userTable" value="#{userController.userlist}"
				var="u">
				<p:column>
					<h:outputText value="#{u.username}" />
				</p:column>
				<p:column>
					<h:outputText value="#{u.password}" />
				</p:column>

				<p:column style="width: 180px;">
					<p:commandButton icon="fa fa-pencil"
						actionListener="#{userController.setSelectedUser(u)}"
						oncomplete="PF('updateDialog').show();" update=":updateDialog"
						style="margin-right: 10px;" />
					<p:commandButton icon="fa fa-key"
						actionListener="#{userController.setSelectedUser(u)}"
						oncomplete="PF('passDialog').show();" update=":passDialog"
						style="margin-right: 10px;" />
					<p:commandButton icon="fa fa-trash"
						actionListener="#{userController.setSelectedUser(u)}"
						oncomplete="PF('delDialog').show();" update=":delDialog" />
				</p:column>
			</p:dataTable>
			<p:column>
				<p:commandButton icon="fa fa-plus-circle"
					actionListener="#{userController.addUser()}"
					oncomplete="PF('addDialog').show();" update=":addDialog" />
			</p:column>
		</h:form>
	</ui:define>
</ui:composition>