src/main/java/ch/ultrasoft/guieditorjsf/model/Role.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.model;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author manigley
 */
@Entity
@Table(name = "roles")
public class Role implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "id_role")
	private Integer id;
	@Column(name = "role")
	private String role;

	public Role() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public String toString() {
		return "Role [id=" + id + "]";
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/AbstractController.java
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.el.ELContext;
import javax.enterprise.context.SessionScoped;
import javax.faces.FacesException;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.servlet.http.HttpServletRequest;

import ch.ultrasoft.guieditorjsf.persistence.DataRepository;

@SessionScoped
public abstract class AbstractController<T> implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private T selectedRecord;
	private List<T> recordList;
	private Class<T> clazz;
	private List<T> filteredRecordList = new ArrayList<>();

	@Inject
	@DataRepository
	private EntityManager em;

	public AbstractController() {
	}

	public AbstractController(Class<T> clazz) {
		this.clazz = clazz;
		try {
			selectedRecord = clazz.newInstance();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
	}

	public void save() {
		EntityTransaction tx = em.getTransaction();
		try {
			tx.begin();
			em.persist(selectedRecord);
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
		}
		clear();
		doHardReload();
		printFacesMessage("Saved", "");
	}

	public void delete(Object o) {
		EntityTransaction tx = em.getTransaction();
		try {
			tx.begin();
			em.remove(o);
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
		}
		clear();
		doHardReload();
		printFacesMessage("DELETED", "");
	}

	protected void printFacesMessage(String summary, String detail) {
		FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage(summary, detail));
	}

	public void clear() {
		try {
			em.clear();
			selectedRecord = clazz.newInstance();
			loadRecordList();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
	}

	public void doHardReload() {
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		try {
			ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void loadRecordList() {
		recordList = em.createQuery("FROM " + clazz.getSimpleName()).getResultList();
		filteredRecordList = recordList;
	}

	public List<T> getRecordList() {
		loadRecordList();
		return recordList;
	}

	public void setRecordList(List<T> recordList) {
		this.recordList = recordList;
	}

	public List<T> getFilteredRecordList() {
		if (filteredRecordList == null) {
			loadRecordList();
		}
		return filteredRecordList;
	}

	public void setFilteredRecordList(List<T> filteredRecordList) {
		this.filteredRecordList = filteredRecordList;
	}

	public T getSelectedRecord() {
		return selectedRecord;
	}

	public void setSelectedRecord(T selectedRecord) {
		this.selectedRecord = selectedRecord;
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/RoleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import ch.ultrasoft.guieditorjsf.model.Role;

/**
 *
 * @author kenny
 */
@Named("roleController")
@SessionScoped
public class RoleController extends AbstractController<Role> implements Serializable {
	
	private static final long serialVersionUID = 1L;

	public RoleController(){
		super(Role.class);
	}
	
	//@TestAnnotation
	public void test() {
		printFacesMessage("Hello", "this is a test");
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/ScheduleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import ch.ultrasoft.guieditorjsf.model.Schedule;

/**
 *
 * @author kenny
 */
@Named("scheduleController")
@SessionScoped
public class ScheduleController extends AbstractController<Schedule> implements Serializable {

	private static final long serialVersionUID = 1L;

	public ScheduleController() {
		super(Schedule.class);
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/controller/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

import ch.ultrasoft.guieditorjsf.bean.UserBean;
import ch.ultrasoft.guieditorjsf.model.Role;
import ch.ultrasoft.guieditorjsf.model.User;
import ch.ultrasoft.guieditorjsf.model.UserRole;
import ch.ultrasoft.guieditorjsf.persistence.DataRepository;

/**
 *
 * @author kenny
 */
@SuppressWarnings("serial")
@Named("userController")
@SessionScoped
public class UserController implements Serializable {

	@Inject
	@DataRepository
	private EntityManager em;

	private String controlPassword;
	private String password;

	@Inject
	UserBean userbean;

	private User selectedUser;
	private boolean isAdmin = false;

	@PostConstruct
	void init() {

		System.out.println("init User");
		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	@SuppressWarnings("unchecked")
	public void updateUser() {
		
		if (password.equals(controlPassword)) {
			selectedUser.setPassword(password);
			selectedUser.setPassword(userbean.getHashMd5(selectedUser
					.getPassword()));
		} 
		EntityTransaction tx = em.getTransaction();
		tx.begin();
		em.merge(selectedUser);
		tx.commit();

		if (isAdmin) {
			UserRole userrole = new UserRole();
			userrole.setUser(selectedUser);
			userrole.setRole(em.find(Role.class, 1));
			tx.begin();
			em.merge(userrole);
			tx.commit();
		} else if (selectedUser.getId() != 0) {
			List<UserRole> listUserRole = em
					.createQuery(
							"FROM UserRole ur WHERE ur.user.id = :idUser AND ur.role.id = 1")
					.setParameter("idUser", selectedUser.getId())
					.getResultList();
			for (UserRole ur : listUserRole) {
				tx.begin();
				em.remove(ur);
				tx.commit();
			}
		}
		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	public void deleteUser() {
		EntityTransaction tx = em.getTransaction();
		@SuppressWarnings("unchecked")
		List<UserRole> lustUserRole = em
				.createQuery("FROM UserRole ur WHERE ur.user.id =:idUser")
				.setParameter("idUser", selectedUser.getId()).getResultList();
		for (UserRole ur : lustUserRole) {
			tx.begin();
			em.remove(ur);
			tx.commit();
		}
		tx.begin();
		em.remove(selectedUser);
		tx.commit();

		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	public void addUser() {
		password = "";
		controlPassword = "";
		isAdmin = false;
		selectedUser = new User();
	}

	public void cancel() {
		selectedUser = new User();
		controlPassword = "";
		password = "1";
	}

	public void updatePassword() {
		if (password == controlPassword) {
			selectedUser.setPassword(password);
		}
	}

	// GETTER & SETTER

	public List<User> getUserlist() {
		return em.createQuery("FROM User u").getResultList();
	}

	public User getSelectedUser() {
		return selectedUser;
	}

	public void setSelectedUser(User selectedUser) {
		this.selectedUser = selectedUser;
	}

	public boolean getAdmin() {
		if (selectedUser != null) {
			List<UserRole> listUserRole = em
					.createQuery(
							"FROM UserRole ur WHERE ur.user.id = :idUser AND ur.role.id = 1")
					.setParameter("idUser", selectedUser.getId())
					.getResultList();

			if (!listUserRole.isEmpty()) {
				return true;
			}
		}
		return false;
	}

	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getControlPassword() {
		return controlPassword;
	}

	public void setControlPassword(String controlPassword) {
		this.controlPassword = controlPassword;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

src/main/java/ch/ultrasoft/guieditorjsf/controller/ValidationController.java
package ch.ultrasoft.guieditorjsf.controller;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.apache.log4j.Logger;

@Named("validationController2")
@SessionScoped
public class ValidationController implements Serializable {

	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger.getLogger(ValidationController.class);

	public void save() {
		LOGGER.debug("save() is called");
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Hello from bean");
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void delete() {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Hello from bean");
		FacesContext.getCurrentInstance().addMessage(null, msg);
		LOGGER.debug("doIt() is called");
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/viewcontroller/RoleViewController.java
package ch.ultrasoft.guieditorjsf.viewcontroller;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;

import ch.ultrasoft.guieditorjsf.viewmodel.UltraDialogModel;
import ch.ultrasoft.guieditorjsf.viewmodel.UltraTableModel;

@SessionScoped
@Named("roleViewController")
public class RoleViewController extends AbstractViewController {

	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger.getLogger(RoleViewController.class);

	public RoleViewController() {

	}

	public UltraTableModel getTableModel() {
		return (UltraTableModel) getService().findViewElement(new Long(7));
	}

	public UltraDialogModel getDialogModel() {
		return (UltraDialogModel) getService().findViewElement(new Long(10));
	}
}

src/main/java/ch/ultrasoft/guieditorjsf/viewcontroller/ViewModelController.java
package ch.ultrasoft.guieditorjsf.viewcontroller;

import java.nio.file.AccessDeniedException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.Stack;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;

import ch.ultrasoft.guieditorjsf.viewmodel.AbstractViewElement;

/**
 * @author manigley
 *
 */
@SessionScoped
@Named("ViewModelController")
public class ViewModelController extends AbstractViewController {

	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger.getLogger(ViewModelController.class);
	
	private Stack<AbstractViewElement> viewElementsPrevStack = new Stack<AbstractViewElement>();
	private Stack<AbstractViewElement> viewElementsNextStack = new Stack<AbstractViewElement>();
	private String classNameNewElement = null;
	private AbstractViewElement nestedElement = null;

	public ViewModelController() {
	}

	public Set<AbstractViewElement> getViewElements() {
		return service.getViewElements();
	}

	@Override
	public void setSelectedViewElement(AbstractViewElement selectedViewElement) {
		if (getSelectedViewElement() != null)
			viewElementsPrevStack.add(getSelectedViewElement());
		super.setSelectedViewElement(selectedViewElement);
	}

	public void setPreviousElement() {
		if (getSelectedViewElement() != null
				&& (viewElementsNextStack.isEmpty() || viewElementsNextStack.peek() != getSelectedViewElement()))
			viewElementsNextStack.push(getSelectedViewElement());
		try {
			super.setSelectedViewElement(refreshAbstractViewElement(viewElementsPrevStack.pop()));
		} catch (Exception e) {
			LOGGER.error("Next viewElement could not been merged", e);
			setPreviousElement();
		}
	}

	public void setNextElement() {
		if (getSelectedViewElement() != null && getSelectedViewElement().getId() != null
				&& !viewElementsPrevStack.isEmpty() && viewElementsPrevStack.peek() != getSelectedViewElement())
			viewElementsPrevStack.push(getSelectedViewElement());
		try {
			super.setSelectedViewElement(refreshAbstractViewElement(viewElementsNextStack.pop()));
		} catch (Exception e) {
			LOGGER.error("Next view Element could not been merged", e);
			setNextElement();
		}
	}

	private AbstractViewElement refreshAbstractViewElement(AbstractViewElement viewElement) {
		if (viewElement != null && viewElement.getId() != null)
			return service.findViewElement(viewElement.getId());
		return viewElement;
	}

	public void addNestedElement() {
		System.out.println("nestedElement: " + nestedElement + " - " + classNameNewElement);
		setMasterViewElement(getSelectedViewElement());
		if (nestedElement != null) {
			LOGGER.info("addNestedElement: " + nestedElement + "( Master: " + getSelectedViewElement() + ")");
			
			if (getSelectedViewElement().getNestedElements() == null)
				getSelectedViewElement().setNestedElements(new ArrayList<Long>());
			
			getSelectedViewElement().getNestedElements().add(nestedElement.getId());
			setSelectedViewElement(service.putViewElement(getSelectedViewElement()));
		} else
			createAbstractViewElement();
	}

	/**
	 * returns a list by instance variable: classNameNewElement
	 * 
	 * @return
	 */
	public Set<AbstractViewElement> getViewElementsByClassName() {
		Set<AbstractViewElement> abstractViewElements = new HashSet<>();
		if (classNameNewElement != null && !classNameNewElement.isEmpty()) {
			abstractViewElements.addAll(service.findViewElementByClass(classNameNewElement));
			if (abstractViewElements.isEmpty() && LOGGER.isInfoEnabled())
				LOGGER.info("getViewElementsByClassName is Empty");
		}
		return abstractViewElements;
	}

	public void createAbstractViewElement() {
		try {
			Class<?> c = Class.forName(classNameNewElement);
			if (c.getSuperclass() == AbstractViewElement.class) {
				setSelectedViewElement((AbstractViewElement) c.newInstance());
			} else
				throw new AccessDeniedException("Class " + classNameNewElement + "is not allowed as nestedElement");
		} catch (ClassNotFoundException | AccessDeniedException | InstantiationException | IllegalAccessException e) {
			LOGGER.error("Faild to createNestedElement as: " + classNameNewElement, e);
		}
		classNameNewElement = null;
	}

	public void cancelUpdate() {
		nestedElement = null;
	}

	public boolean isPrevStackEmpty() {
		return viewElementsPrevStack.isEmpty();
	}

	public boolean isNextStackEmpty() {
		return viewElementsNextStack.isEmpty();
	}

	public String getClassNameNewElement() {
		return classNameNewElement;
	}

	public void setClassNameNewElement(String classNameNewElement) {
		this.classNameNewElement = classNameNewElement;
	}

	public AbstractViewElement getNestedElement() {
		return nestedElement;
	}

	public void setNestedElement(AbstractViewElement nestedElement) {
		this.nestedElement = nestedElement;
	}
}

src/main/webapp/inputvalidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>JSF</title>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	<h:outputStylesheet library="awesome" name="css/font-awesome.css" />
</h:head>


<h:body>

	<p:growl id="message" life="3000" />

	<p:layout id="mainLayout" fullPage="true">

		<p:layoutUnit position="north" header="Messages">
			<h:form>
				<p:commandButton value="Growl" icon="fa fa-arrow-circle-right"
					action="inputvalidationGrowl?faces-redirect=true" ajax="false" />
			</h:form>
		</p:layoutUnit>
		<p:layoutUnit position="center">
			<h:form>
				<h:panelGroup id="panel">
					<p:panelGrid columns="4" styleClass="ui-noborder">
						<h:outputLabel for="name" value="Name:" style="font-weight:bold" />
						<p:inputText id="name" value="#{text}" required="true"
							label="Name" />
						<p:message for="name" />
						<h:outputText value="#{text}" />

						<h:outputLabel for="textonly" value="text only:"
							style="font-weight:bold" />
						<p:inputText id="textonly" value="#{textonlyRegex}"
							required="true" label="text only" requiredMessage="is text only!"
							validatorMessage="is text only!">
							<f:validateRegex pattern="^[a-zA-Z]+$" for="textonly" />
						</p:inputText>
						<p:message for="textonly" />
						<h:outputText value="#{textonlyRegex}" />

						<h:outputLabel for="integer" value="integer:"
							style="font-weight:bold" />
						<p:inputText id="integer" value="#{integerRegex}" required="true"
							label="integer" requiredMessage="must be a integer!"
							validatorMessage="must be a integer!">
							<f:validateRegex pattern="^\d+$" for="integer" />
						</p:inputText>
						<p:message for="integer" />
						<h:outputText value="#{integerRegex}" />

						<h:outputLabel for="double" value="double:"
							style="font-weight:bold" />
						<p:inputText id="double" value="#{doubleRegex}" required="true"
							label="double" requiredMessage="must be a double!"
							validatorMessage="must be a double!">
							<f:validateRegex pattern="^\d+(\.)?(\d)?$" for="double" />
						</p:inputText>
						<p:message for="double" />
						<h:outputText value="#{doubleRegex}" />

						<h:outputLabel for="email" value="e-mail:"
							style="font-weight:bold" />
						<p:inputText id="email" value="#{emailRegex}" required="true"
							label="double" requiredMessage="must be an e-mail!"
							validatorMessage="must be an e-mail!">
							<f:validateRegex
								pattern="^([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})$"
								for="double" />
						</p:inputText>
						<p:message for="double" />
						<h:outputText value="#{doubleRegex}" />
					</p:panelGrid>
				</h:panelGroup>
				<p:commandButton icon="fa fa-save" value="ajax"
					validateClient="true" update="panel"
					actionListener="#{validationController.save()}" />
			</h:form>
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/inputvalidationGrowl.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>JSF</title>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	<h:outputStylesheet library="awesome" name="css/font-awesome.css" />
</h:head>


<h:body>

	<p:growl id="message" life="3000" />

	<p:layout id="mainLayout" fullPage="true">

		<p:layoutUnit position="north" header="Growl">
			<h:form>
				<p:commandButton icon="fa fa-arrow-circle-right" value="Message"
					action="inputvalidation?faces-redirect=true" ajax="false" />
			</h:form>
		</p:layoutUnit>
		<p:layoutUnit position="center">
			<h:form>
				<h:panelGroup id="panel">
					<p:panelGrid columns="3" styleClass="ui-noborder">
						<h:outputLabel for="name" value="Name:" style="font-weight:bold" />
						<p:inputText id="name" value="#{text}" required="true"
							label="Name" />
						<h:outputText value="#{text}" />

						<h:outputLabel for="textonly" value="text only:"
							style="font-weight:bold" />
						<p:inputText id="textonly" value="#{textonlyRegex}"
							required="true" label="text only" requiredMessage="is text only!"
							validatorMessage="is text only!">
							<f:validateRegex pattern="^[a-zA-Z]+$" for="textonly" />
						</p:inputText>
						<h:outputText value="#{textonlyRegex}" />

						<h:outputLabel for="integer" value="integer:"
							style="font-weight:bold" />
						<p:inputText id="integer" value="#{integerRegex}" required="true"
							label="integer" requiredMessage="must be a integer!"
							validatorMessage="must be a integer!">
							<f:validateRegex pattern="^\d+$" for="integer" />
						</p:inputText>
						<h:outputText value="#{integerRegex}" />

						<h:outputLabel for="double" value="double:"
							style="font-weight:bold" />
						<p:inputText id="double" value="#{doubleRegex}" required="true"
							label="double" requiredMessage="must be a double!"
							validatorMessage="must be a double!">
							<f:validateRegex pattern="^\d+(\.)?(\d)?$" for="double" />
						</p:inputText>
						<h:outputText value="#{doubleRegex}" />

						<h:outputLabel for="email" value="e-mail:"
							style="font-weight:bold" />
						<p:inputText id="email" value="#{emailRegex}" required="true"
							label="double" requiredMessage="must be an e-mail!"
							validatorMessage="must be an e-mail!">
							<f:validateRegex
								pattern="^([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})$"
								for="double" />
						</p:inputText>
						<h:outputText value="#{doubleRegex}" />
					</p:panelGrid>
				</h:panelGroup>
				<p:commandButton icon="fa fa-save" value="no ajax"
					validateClient="true" update="panel" ajax="false"
					actionListener="#{validationController.save()}" />


			</h:form>

			<h:form>
				<p:commandButton icon="fa fa-save" value="hello" ajax="false"
					actionListener="#{tableController.hello()}" />
					
					<p:inputText value="#{tableController.hello}" />

				<p:dataTable value="#{tableController.viewElements}" var="r"
					paginator="true"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,15,20,25" rows="10">
					<p:column headerText="id" filterBy="#{r.id}"
						filterMatchMode="contains">
						<h:outputText value="#{r.id}" />
					</p:column>
				</p:dataTable>

			</h:form>
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/test.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html">
	<h:head>
		<f:facet name="first">
			<meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
			<link type="text/css" rel="stylesheet"
				href="../resources/css/style.css" />
			<h:outputStylesheet library="awesome" name="css/font-awesome.css" />
			<title>JSFCompositeComponents</title>
		</f:facet>
	</h:head>

	<h:body>

		<p:growl id="message" life="5000" autoUpdate="true" globalOnly="true"
			showDetail="true" />


		<p:layout id="mainLayout" fullPage="true">

			<p:layoutUnit position="center"
				header="Experiment JSFCompositeComponents">
				<p:dataTable value="#{xmlViewModelController.viewElements}" var="r">
					<p:column>
						<h:outputText value="#{r.id}" />
					</p:column>
				</p:dataTable>

			</p:layoutUnit>
		</p:layout>
	</h:body>

</f:view>
</html>